### ISSUE TITLE
Can add Windows file naming technique to rename .envdev to .env in README.md

### ISSUE THREAD

**Issue by twaritwaikar** [TimRuswick/SANCTUM#5]
Windows does not allow naming files as `.extention` and instead forces you to name them as `filename.extention`.

But Windows does provide a way to name files as `.extension` and that is by renaming them as `.extension.`
Windows will automatically remove the last period for you.

This information can be added to the README.

**Comment by Ratstail91** [comment]
Oddly enough, I rename it using sublime text, and don't have a problem.

**Comment by twaritwaikar** [comment]
Yes, you can use advanced text editors to do that but I found this way to be straightforward and to the point, which doesn't require any external help

**Comment by Ratstail91** [comment]
@IronicallySerious I've added this issue to the notes for the next meeting.

**Comment by some1chan** [comment]
@IronicallySerious thanks for that tip, I never knew that was possible! Added it in the dev and master branches.
